### PR TITLE
feat: allow overriding default transformers with same name

### PR DESCRIPTION
**Pull request by chaitanyadeorukhkar**
**What**: Override the default transformer when a custom transformer with the same name exists

**Why**: I wanted to override the default Twitter transformer with my own to make changes to the oembed API call but because a default transformer exists for it, it ignores the custom transformer

**How**: 
1. Create an array of `customTransformerNames` which stores all the names of user-created transformers
2. Filter out the default transformers who's name matches the ones created by the user

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged
      

Wanted to get some early feedback if this is the right approach or if there's an alternative so that I can go ahead with writing the documentation and tests

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
@chaitanyadeorukhkar Can you tell me what you wanted to change to the Twitter transformer?

I think we can probably make a change on that transformer only instead of making this big change.

**Comment by chaitanyadeorukhkar** [comment]
@MichaelDeBoey thanks for the quick response! I wanted to add a `theme=dark` in the URL params but it doesn't seem fair to make that change for everyone who uses this. Which brought me to the conclusion of having the ability to override the default transformers

**Comment by MichaelDeBoey** [comment]
@chaitanyadeorukhkar We could add support for that one via [transformer options](https://github.com/MichaelDeBoey/gatsby-remark-embedder#services) like we have for [Twitch](https://github.com/MichaelDeBoey/gatsby-remark-embedder#options)

**Comment by MichaelDeBoey** [comment]
@chaitanyadeorukhkar We could add support for that one via [transformer options](https://github.com/MichaelDeBoey/gatsby-remark-embedder#services) like we have for [Twitch](https://github.com/MichaelDeBoey/gatsby-remark-embedder#options)

Closing this in favor of a new PR for that

**Pull request closed without merging**
