### PR TITLE
refactor(tests): Refactor snapshot tests

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
@kentcdodds Because of your comment (https://github.com/MichaelDeBoey/gatsby-remark-embedder/pull/43#discussion_r355135872), I started looking in putting all snapshot tests into the [plugin test file](https://github.com/MichaelDeBoey/gatsby-remark-embedder/blob/2c60dee771ad0892444c937d529244cc49fe7a8c/src/__tests__/plugin.js).

Like I thought, this would make it really big and inconvenient (going from 138 to 205 lines).

I agree the [plugin snapshot file](https://github.com/MichaelDeBoey/gatsby-remark-embedder/blob/2c60dee771ad0892444c937d529244cc49fe7a8c/src/__tests__/__snapshots__/plugin.js.snap) is also getting bigger with every test we add, but that's another file and  doesn't make the tests bloated.

I also agree with the fact that large snapshot files should be avoided, like you explain in your [_Effective Snapshot Testing_ blogpost](https://kentcdodds.com/blog/effective-snapshot-testing).

A possible solution would be to add the snapshot tests to the transformer-specific tests files (like I did in a0a959f3).
This would also create a small snapshot file for each transformer.
But on the other hand, this solution will separate what's really a plugin test from the other plugin tests.

Would really love to have your opinion on this one, on what you think would be the best way to go.

### CODE REVIEW

**Comment by kentcdodds** [comment]
I would recommend using toMatchInlineSnapshot in individual transformer tests and then just have a simple one for the main test. That would be super simple and not sided from the big drawbacks from snapshots. In any case, I don't think there's any good reason to use non-inline snapshots.

**Comment by MichaelDeBoey** [comment]
So keep the kitchensink and custom transformer one in the main file and move all the others to transformer specific files?

Now that I think of it, we could test all supported variants in the specific fixtures instead of just a single line and keep the main variant (like we use in the docs) in the kitchensink.

**Comment by MichaelDeBoey** [comment]
@kentcdodds I've moved all plugin tests to their own specific transformer files and created some helpers to remove test code duplication.

I think we could now add extra lines to every fixture, so it contains all supported (and maybe also the not-supported) links we have in our `url validation` tests?

I know we double test them this way, but it can be some sort of extra confidence.

**Comment by kentcdodds** [comment]
Sorry, I don't have the bandwidth to provide any more feedback here. I'm sure you'll make a good choice 👍

**Pull request merged**
