### PR TITLE
Refactored the logo

### PR DESCRIPTION
**Pull request by caneco**
Hello, here is the refactored version with the full package name 😄 

image

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
Hi @caneco!

Thanks for the awesome refactor of the logo. 🙂👊

Would it be possible to add a 1280×640px variant to use as the [social preview](https://help.github.com/en/articles/customizing-your-repositorys-social-media-preview) please? 🤔

Thanks for all the effort you're putting into this! 🙂

**Comment by caneco** [comment]
Here it is… 😄 

gatsby-remark-embedder

**Comment by MichaelDeBoey** [comment]
@caneco Could you add it to the repo too please? 🤔

Thanks! 👊

**Comment by MichaelDeBoey** [comment]
Thanks for the great logo @caneco! 🙂
It's really appreciated! 👊

**Pull request merged**
